//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


/// <summary>
/// Avatar associated with a IMDb name.
/// Includes url linking to the image, the width and height of the image in pixels.
/// </summary>
public partial class Avatar : GraphQLTypeBase
{
    [GraphQLMember("url")]
    [JsonPropertyName("url")]
    public string Url { get; set; }

    [GraphQLMember("width")]
    [JsonPropertyName("width")]
    public int Width { get; set; }

    [GraphQLMember("height")]
    [JsonPropertyName("height")]
    public int Height { get; set; }

}
