//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


/// <summary>
/// The certificates is the ratings certificates given to titles within each country.
/// For example a title may be given a 'PG-13' rating in the 'US' region (by the MPA)
/// </summary>
public partial class Certificate : GraphQLTypeBase
{
    [GraphQLMember("country")]
    [JsonPropertyName("country")]
    public Country Country { get; set; }

    [GraphQLMember("rating")]
    [JsonPropertyName("rating")]
    public string Rating { get; set; }

}
