//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


public partial class Country : GraphQLTypeBase
{
    /// <summary>
    /// ISO 3166-1 alpha-2 codes (two-letter).
    /// </summary>
    [GraphQLMember("code")]
    [JsonPropertyName("code")]
    public string Code { get; set; }

    /// <summary>
    /// English short name officially used by the ISO 3166 Maintenance Agency (ISO 3166/MA)
    /// </summary>
    [GraphQLMember("name")]
    [JsonPropertyName("name")]
    public string Name { get; set; }

}
