//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


/// <summary>
/// The credits for this title organized by category.
/// </summary>
public partial class Credit : GraphQLTypeBase
{
    /// <summary>
    /// A IMDB name that the person was credited.
    /// </summary>
    [GraphQLMember("name")]
    [JsonPropertyName("name")]
    public Name Name { get; set; }

    /// <summary>
    /// Category name, e.g. director, writer, actor, actress
    /// </summary>
    [GraphQLMember("category")]
    [JsonPropertyName("category")]
    public string Category { get; set; }

    /// <summary>
    /// A list of characters.
    /// </summary>
    [GraphQLMember("characters")]
    [JsonPropertyName("characters")]
    public List<string> Characters { get; set; }

    /// <summary>
    /// For series we include number of episodes that the person was credited.
    /// </summary>
    [GraphQLMember("episodes_count")]
    [JsonPropertyName("episodes_count")]
    public int? Episodes_count { get; set; }

}
