//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


/// <summary>
/// The reviews score of title from Metacritic.com
/// </summary>
public partial class CriticReview : GraphQLTypeBase
{
    [GraphQLMember("score")]
    [JsonPropertyName("score")]
    public int Score { get; set; }

    [GraphQLMember("review_count")]
    [JsonPropertyName("review_count")]
    public int Review_count { get; set; }

}
