//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Linq2GraphQL.Client;
using Linq2GraphQL.Client.Common;

namespace DemoNamespace;


/// <summary>
/// The IMDb Rating for the title.
/// </summary>
public partial class Rating : GraphQLTypeBase
{
    /// <summary>
    /// Between 1 and 10 and given to one decimal place.
    /// </summary>
    [GraphQLMember("aggregate_rating")]
    [JsonPropertyName("aggregate_rating")]
    public double Aggregate_rating { get; set; }

    /// <summary>
    /// The number of IMDb users who have voted on this title.
    /// </summary>
    [GraphQLMember("votes_count")]
    [JsonPropertyName("votes_count")]
    public int Votes_count { get; set; }

}
