//---------------------------------------------------------------------
// This code was automatically generated by Linq2GraphQL
// Please don't edit this file
// Github:https://github.com/linq2graphql/linq2graphql.client
// Url: https://linq2graphql.com
//---------------------------------------------------------------------

using System.Collections.Generic;
using System;
using Linq2GraphQL.Client;

namespace DemoNamespace;

public class QueryMethods
{
    private readonly GraphClient client;

    public QueryMethods(GraphClient client)
    {
        this.client = client;
    }

    public GraphQuery<Title> Title(string id)
    {
	    var arguments = new List<ArgumentValue>
        {
    	    new("id","ID!", id),
        };

        return new GraphQuery<Title>(client,  "title", OperationType.Query, arguments); 
    }

    public GraphQuery<List<Title>> Titles(List<string> ids)
    {
	    var arguments = new List<ArgumentValue>
        {
    	    new("ids","[String!]!", ids),
        };

        return new GraphQuery<List<Title>>(client,  "titles", OperationType.Query, arguments); 
    }

    public GraphQuery<Name> Name(string id)
    {
	    var arguments = new List<ArgumentValue>
        {
    	    new("id","ID!", id),
        };

        return new GraphQuery<Name>(client,  "name", OperationType.Query, arguments); 
    }

    public GraphQuery<List<Name>> Names(List<string> ids)
    {
	    var arguments = new List<ArgumentValue>
        {
    	    new("ids","[String]!", ids),
        };

        return new GraphQuery<List<Name>>(client,  "names", OperationType.Query, arguments); 
    }

    }
